=== stanislavhristov00/XML_COURSE_WORK/wonders.dtd
<?xml version="1.0" encoding="UTF-8"?>
<!ELEMENT catalog (continents, wonders)>

<!ELEMENT continents (continent, continent, continent, continent, continent, continent, continent)>
<!ELEMENT continent (#PCDATA)>
<!ATTLIST continent id ID #REQUIRED>

<!ELEMENT wonders (wonder+)>
<!ELEMENT wonder (name, location, description, history, availability, images)>
<!ATTLIST wonder contRef IDREF #IMPLIED>

<!ELEMENT name (#PCDATA)>

<!ELEMENT location (city, region, country)>
<!ELEMENT city (#PCDATA)>
<!ELEMENT region (#PCDATA)>
<!ELEMENT country (#PCDATA)>

<!ELEMENT description (#PCDATA)>

<!ELEMENT history (#PCDATA)>

<!ELEMENT availability (#PCDATA)>

<!ELEMENT images (image*)>
<!ELEMENT image EMPTY>
<!ATTLIST image src ENTITY #REQUIRED>

<!NOTATION JPG SYSTEM "image/jpeg">
<!ENTITY test_photo SYSTEM "images/1.jpeg" NDATA JPG>
<!ENTITY test_photo2 SYSTEM "images/2.jpeg" NDATA JPG>

=== stanislavhristov00/XML_COURSE_WORK/wonders.xml
<?xml version="1.0" encoding="UTF-8"?>
<?xml-stylesheet type="text/xsl" href="transform.xsl"?>
<!DOCTYPE catalog SYSTEM "wonders.dtd">
<catalog>
    <continents>
        <continent id="AS">Азиа</continent>
        <continent id="AF">Африка</continent>
        <continent id="NA">Северна Америка</continent>
        <continent id="SA">Южна Америка</continent>
        <continent id="AN">Антарктида</continent>
        <continent id="EU">Европа</continent>
        <continent id="AU">Австралия</continent>
    </continents>
    <wonders>
        <wonder contRef="AS">
            <name></name>
            <location>
                <city></city>
                <region></region>
                <country></country>
            </location>
            <description>alabala</description>
            <history>djigir igi</history>
            <availability></availability>
            <images>
                <image src="test_photo" />
                <image src="test_photo2"/>
            </images>
        </wonder>
        <wonder contRef="AS">
            <name></name>
            <location>
                <city></city>
                <region></region>
                <country></country>
            </location>
            <description>alabala</description>
            <history>djigir igi</history>
            <availability></availability>
            <images>
                <image src="test_photo" />
                <image src="test_photo2"/>
            </images>
        </wonder>
    </wonders>
</catalog>
